"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { useState } from "react";
// import NextProgress from "nextjs-progressbar"



const inter = Poppins({ subsets: ["latin"], weight: ["300" , "700"] });

// export const metadata = {
//   title: "Zewd-app",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [updateCart,setUpdateCart]=useState(false);
  return (
    <ClerkProvider>
      <html lang="en">
        {/* <NextProgress/> */}
        <body className={inter.className}>
          <UpdateCartContext.Provider value={{updateCart,setUpdateCart}}>
            {children}
          <Toaster />
          </UpdateCartContext.Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
